accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name="accountsHome"),
    path('createAccount/', views.createAccount, name="createAccount"),
    path('checkUserName/', views.checkUserName, name="checkUserName"),
    path('checkEmail/', views.checkEmail, name="checkEmail"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('addUser/', views.addUser, name='addUser'),
    path('resetAccount/', views.resetAccount, name='resetAccount'),
    path('resetPass/', views.resetPass, name='resetPass'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog import views

urlpatterns = [
    path('', views.home, name='blogHome'),
    path('details/', views.blogDetails, name='blogDetails'),
    path('addComment/', views.addComment, name='addComment'),
    path('deleteComment/', views.deleteComment, name='deleteComment'),
]

chaitanya/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('home/',include('home.urls')),
    path('newsletters/',include('newsletters.urls')),
    path('blogs/',include('blog.urls')),
    path('contest/',include('contest.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from home import views

urlpatterns = [
    path('', views.home, name='Home'),
    path('gallery/', views.gallery, name='Gallery'),
    path('notifications/', views.notifications, name='Notifications'),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime

# Create your models here.


class Gallery(models.Model):
    img = models.ImageField(upload_to="static/media/gallery/")
    time = models.DateTimeField(default=datetime.now)
    
    def __str__(self):
        return str(self.pk)

    @classmethod
    def create(cls, img):
        gallery = cls(img=img)
        return gallery

profiles/models.py
from os import rename
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    firstName = models.CharField(max_length=30, verbose_name='First Name')
    lastName = models.CharField(blank=True, max_length=30, verbose_name='Last Name')
    email = models.EmailField(unique=True, verbose_name='Email ID')
    phone = models.CharField(max_length=13)
    resume = models.FileField(upload_to="static/media/resume")

    def __str__(self):
        return self.user.username

    @classmethod
    def create(cls, user, first_name, last_name, email_id, phone_number,resume):
        profile = cls(user=user, firstName=first_name, lastName=last_name,
                      email=email_id, phone=phone_number,resume=resume)
        return profile

accounts/views.py
from collections import UserList
from django.shortcuts import render
from django.http import HttpResponse
import json
from . mailer import send_mail
from django.apps import apps
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from random import randint
from django.contrib.auth import logout

# Create your views here.

Profile = apps.get_model('profiles', 'Profile')


def random_with_N_digits(n):
    range_start = 10**(n-1)
    range_end = (10**n)-1
    return randint(range_start, range_end)


def resetAccount(request):
    context = {
        "title": "SOECE: Society Of Electronics And Communications"
    }

    email = request.POST.get("email")

    cnt = 0

    if Profile.objects.filter(email=email).exists():
        cnt = 1

    if cnt == 0:
        context["err"] = "no such account exists"
        return render(request, "registration/login.html", context)

    otp = random_with_N_digits(6)
    context["otp"] = otp
    context["username"] = Profile.objects.filter(email=email)[0].user
    print(otp)
    print(email)
    print(context["username"])
    send_mail("Reset Password From SOECE", "Your previous username is {} and otp is {}".format(context["username"], otp), [email, ])
    return render(request, "accounts/resetAccount.html", context)


def resetPass(request):
    context = {
        "title": "SOECE: Society Of Electronics And Communications"
    }

    username = request.POST.get("username")
    password = request.POST.get("password1")
    user = User.objects.get(username=username)
    user.set_password(password)
    user.save()
    user = authenticate(username=username, password=password)
    login(request, user)
    return render(request, "home/home.html", context)


def home(request):
    context = {
        "title": "SOECE: Society Of Electronics And Communications"
    }
    return render(request, "accounts/home.html", context)


def logout_view(request):
    logout(request)
    context = {
        "title": "SOECE: Society Of Electronics And Communications"
    }
    return render(request, "registration/login.html", context)


def checkUserName(request):
    username = request.POST.get("username")
    cnt = 0
    if User.objects.filter(username=username).exists():
        cnt = 1
    data = json.dumps({
        'cnt': cnt,
    })
    return HttpResponse(data)


def checkEmail(request):
    email = request.POST.get("email")
    cnt = 0
    if Profile.objects.filter(email=email).exists():
        cnt = 1
    data = json.dumps({
        'cnt': cnt,
    })
    return HttpResponse(data)


def addUser(request):
    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        user = user_form.save()
        user.save()
        firstName = request.POST.get('firstName')
        lastName = request.POST.get('lastName')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        resume = request.FILES['resume']
        profile = Profile.objects.create(
            user=user, firstName=firstName, lastName=lastName, email=email, phone=phone, resume=resume)
        profile.save()
        username = user_form.cleaned_data['username']
        password = user_form.cleaned_data['password1']
        user = authenticate(username=username, password=password)
        login(request, user)
        return render(request, 'home/home.html', {"title": "SOECE: Society Of Electronics And Communications"})
    else:
        return render(request, 'accounts/home.html', {"title": "SOECE: Society Of Electronics And Communications"})


def createAccount(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password1')
        firstName = request.POST.get('firstName')
        lastName = request.POST.get('lastName')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        otp = random_with_N_digits(6)
        send_mail("Thanks for joining SOECE", otp, [email, ])
        context = {
            "title": "SOECE: Society Of Electronics And Communications",
            "username": username,
            "password": password,
            "firstName": firstName,
            "lastName": lastName,
            "email": email,
            "phone": phone,
            "otp": otp,
        }
        return render(request, 'accounts/otpConfirm.html', context)
    else:
        return render(request, 'accounts/home.html', {"title": "SOECE: Society Of Electronics And Communications"})


def profile(request):
    context = {
        "title": "SOECE: Society Of Electronics And Communications"
    }
    return render(request, "home/home.html", context)

home/views.py
from typing import ContextManager
from django.shortcuts import render, HttpResponse
import json
from .models import Gallery
from django.apps import apps
from datetime import date, datetime, timezone
import pytz


Blog = apps.get_model('blog', 'Blog')
Newsletter = apps.get_model('newsletters', 'Newsletter')
Contest = apps.get_model('contest', 'Contest')

# Create your views here.


def home(request):
    context = {
        "title": "SOECE: Society Of Electronics And Communications"
    }
    return render(request, 'home/home.html', context)


def gallery(request):
    context = {}
    lmt = 10
    query = Gallery.objects.order_by('-pk')
    lmt = min(lmt, query.count())
    query = query[:lmt]

    context["img"] = []

    for q in query:
        context["img"].append(q.img.url)

    return HttpResponse(json.dumps(context))


def notifications(request):
    utc = pytz.UTC

    context = {}
    context["blogs"] = []
    context["newsletters"] = []

    lmt_from_blog = 10
    lmt_from_newsletter = 10
    lmt_from_contest = 10

    blog = Blog.objects.order_by('-pk')
    lmt_from_blog = min(lmt_from_blog, blog.count())
    blog = blog[:lmt_from_blog]

    newsletter = Newsletter.objects.order_by('-pk')
    lmt_from_newsletter = min(lmt_from_newsletter, newsletter.count())
    newsletter = newsletter[:lmt_from_newsletter]

    contest = Contest.objects.order_by('-pk')
    lmt_from_contest = min(lmt_from_contest, contest.count())
    contest = contest[:lmt_from_newsletter]

    now = utc.localize(datetime.now())

    for b in blog:
        data = {}
        data["heading"] = b.heading
        data["url"] = "blogs/details/?blog=" + str(b.pk)
        diff = (now - b.time).days

        if diff < 10:
            data["new"] = 1
        else:
            data["new"] = 0

        context["blogs"].append(data)

    for n in newsletter:
        data = {}
        data["heading"] = n.heading
        data["url"] = "newsletters/details?newsletter=" + str(n.pk)

        diff = (now - n.time).days

        if diff < 10:
            data["new"] = 1
        else:
            data["new"] = 0

        context["newsletters"].append(data)

    for n in contest:
        data = {}
        data["heading"] = n.heading
        data["url"] = "contest/details/?contest=" + str(n.pk)

        diff = (now - n.time).days

        if diff < 10:
            data["new"] = 1
        else:
            data["new"] = 0

        context["newsletters"].append(data)

    return HttpResponse(json.dumps(context))

templates/accounts/home.html
{% extends 'accounts/basic.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}


{% block css %}{%endblock%}

{%block header%}
<header class="site-header mo-left header">
	<div class="sticky-header main-bar-wraper header-curve navbar-expand-lg">
		<div class="main-bar clearfix bg-primary">
			<div class="container clearfix">
				<!-- website logo -->
				<div class="logo-header mostion">
					<a href="/"><img src="{%static 'images/logo.png'%}" alt="" style="height: 72px; width: 72px;"></a>
				</div>

				<!-- main nav -->
				<div class="header-nav navbar-collapse collapse justify-content-end" id="navbarNavDropdown">
					<div class="logo-header d-md-block d-lg-none">
						<a href="/"><img src="{%static 'images/logo.png'%}" alt=""></a>
					</div>
					<ul class="nav navbar-nav">
						<li> <a href="/">Home</a></li>
						<li> <a href="/blogs">Blogs</a></li>
						<li> <a href="/newsletters">Newsletters</a></li>
						<li> <a href="/contest">Contests</a></li>
						{%if user.is_authenticated%}
						<li> <a href="/accounts/logout">Logout</a></li>
						{%else%}
						<li> <a href="/accounts/login">Login</a></li>
						{%endif%}
					</ul>
				</div>
			</div>
		</div>
	</div>
</header>

{%endblock%}


{% block body%}
<div class="section-full content-inner contact-page-8 bg-white">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-12">
				<div class="row">
					<div class="col-lg-12 col-md-12 m-b30">
						<div class="icon-bx-wraper expertise bx-style-1 p-a20 radius-sm">
							<div class="icon-content">
								<h5 class="dlab-tilte">
									<span class="icon-sm text-primary"><i class="ti-location-pin"></i></span>
									NIT, JALANDHAR
								</h5>
								<p>Grand Trunk Road, Barnala - Amritsar Bypass Rd, Jalandhar, Punjab 144011 / India </p>
								<h6 class="m-b15 text-black font-weight-400"><i class="ti-alarm-clock"></i> Office Hours
								</h6>
								<p class="m-b0">Mon To Sun - 24 Hr</p>
								<p>National Holidays - Closed</p>
							</div>
						</div>
					</div>
					<div class="col-lg-12 col-md-6 m-b30">
						<div class="icon-bx-wraper expertise bx-style-1 p-a20 radius-sm">
							<div class="icon-content">
								<h5 class="dlab-tilte">
									<span class="icon-sm text-primary"><i class="ti-email"></i></span>
									E-mail
								</h5>
								<p class="m-b0">webmaster@nitj.ac.in</p>
							</div>
						</div>
					</div>
					<div class="col-lg-12 col-md-6 m-b30">
						<div class="icon-bx-wraper expertise bx-style-1 p-a20 radius-sm">
							<div class="icon-content">
								<h5 class="dlab-tilte">
									<span class="icon-sm text-primary"><i class="ti-mobile"></i></span>
									Phone Numbers
								</h5>
								<p class="m-b0">+91-181-2690324</p>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-lg-8 col-md-12 m-b30" id="form_container">
				<form class="inquiry-form wow fadeInUp" data-wow-delay="0.2s" action="/accounts/createAccount/"
					method="POST" enctype="multipart/form-data" onsubmit="return VerifyData();">
					{% csrf_token %}
					<h3 class="title-box font-weight-300 m-t0 m-b10">SIGNUP <span class="bg-primary"></span></h3>
					<p>CREATE NEW ACCOUNT FROM HERE</p>
					<div class="row">

						<!-- username -->
						<div class="col-lg-12 col-md-12">
							<div class="form-group" id="div_id_name">
								<div class="input-group" id="div_id_username">
									<span class="input-group-addon"><i class="ti-star text-primary"></i></span>
									<input name="username" type="text" required class="form-control"
										placeholder="User Name" id="id_username">
								</div>
							</div>
						</div>

						<!-- password -->
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<div class="input-group" id="div_id_password1">
									<span class="input-group-addon"><i class="ti-lock text-primary"></i></span>
									<input name="password1" type="password" required class="form-control"
										placeholder="Password" id="id_password1">
									<span class="input-group-addon"><i class="fa fa-eye text-primary"
											onclick="changeType(this,document.getElementsByName('password1')[0]);"></i></span>
								</div>
							</div>
						</div>

						<!-- confirm password -->
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<div class="input-group" id="div_id_password2">
									<span class="input-group-addon"><i class="ti-lock text-primary"></i></span>
									<input name="password2" type="password" required class="form-control"
										placeholder="Confirm Password" id="id_password2">
									<span class="input-group-addon"><i class="fa fa-eye text-primary"
											onclick="changeType(this,document.getElementsByName('password2')[0]);"></i></span>
								</div>
							</div>
						</div>

						<!-- first name -->
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<div class="input-group" id="div_id_firstName">
									<span class="input-group-addon"><i class="ti-user text-primary"></i></span>
									<input name="firstName" type="text" required class="form-control"
										placeholder="First Name" id="id_firstName">
								</div>
							</div>
						</div>

						<!-- last name -->
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<div class="input-group" id="div_id_lastName">
									<span class="input-group-addon"><i class="ti-user text-primary"></i></span>
									<input name="lastName" type="text" class="form-control" placeholder="Last Name"
										id="id_lastName">
								</div>
							</div>
						</div>

						<!-- email address -->
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<div class="input-group" id="div_id_email">
									<span class="input-group-addon"><i class="ti-email text-primary"></i></span>
									<input name="email" type="email" class="form-control" required
										placeholder="Your Email Id" id="id_email">
								</div>
							</div>
						</div>

						<!-- phone number -->
						<div class="col-lg-6 col-md-6">
							<div class="form-group">
								<div class="input-group" id="div_id_phone">
									<span class="input-group-addon"><i class="ti-mobile text-primary"></i></span>
									<input name="phone" type="tel" class="form-control" required placeholder="Phone"
										id="id_phone">
								</div>
							</div>
						</div>

						<div class="col-lg-12 col-md-12">
							<button name="submit" type="submit" value="Submit" class="site-button button-md">
								<span>SIGNUP!</span> </button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{%endblock%}


{% block footer%}
<!-- Footer -->
<footer class="site-footer footer-full">
	<div class="p-tb60 bg-black">
		<div class="container">
			<div class="row">
				<div class="col-md-6 text-md-left text-center footer-logo">
					<img src="{%static 'images/logo.png'%}" alt="" width="100">
					<p class="m-b0 m-t10">Copyright © 2021</p>
				</div>
				<div class="col-md-6 text-md-right text-center">
					<div class="widget-link ">
						<p>
							Developed By
							<a target="_blank" href="https://www.linkedin.com/in/prince-mishra-7379101ab/">Prince Mishra</a>, and
							<a target="_blank" href="https://www.linkedin.com/in/nishant-6013b61a3/">Nishant</a>
						</p>
						<p>
							Idea by
							<a target="_blank" href="https://www.linkedin.com/in/sourav-goyal-61b469196/">Sourav Goyal</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- Footer END -->

{%endblock%}



{% block script %}

<script>
	function VerifyData() {
		// username verification
		let userName = document.getElementsByName("username")[0].value;

		if (userName.length > 150) {
			alert("username must be less than 150 characters");
			return false;
		}

		for (let index = 0; index < userName.length; index++) {
			const element = userName[index];

			if ((element >= 'a' && element <= 'z') || (element >= 'A' && element <= 'Z') || (element >= 0 && element <=
					9) || element == '@' || element == '.' || element == '+' || element == '-' || element == '_') {
				continue;
			}

			alert("username can contain letters, digits, @, ., +, -, _ only");
			return false;
		}

		response = JSON.parse(ajaxRequest("/accounts/checkUserName/", {
			"username": userName,
		}));


		if (response["cnt"] > 0) {
			alert("same username already exists");
			return false;
		}

		// password verification
		let pass1 = document.getElementsByName("password1")[0].value;
		let pass2 = document.getElementsByName("password2")[0].value;

		if (pass1.length < 8) {
			alert("Your password must contain at least 8 characters.");
			return false;
		}

		flag = true;

		for (let index = 0; index < pass1.length; index++) {
			const element = pass1[index];

			if (element >= 0 && element <= 9) continue;
			else flag = false;
		}

		if (flag) {
			alert("Your password can’t be entirely numeric");
			return false;
		}

		if (pass1 != pass2) {
			alert("Passwords are different");
			return false;
		}

		for (let l = 0, r = pass1.length - 1; r < userName.length; l++, r++) {
			var flag = true;

			for (let i = l; i <= r; i++) {
				if (pass1[i - l] != userName[i]) {
					flag = false;
					break;
				}
			}

			if (flag) {
				alert("Your password can’t be too similar to your other personal information.");
				return false;
			}
		}

		for (let l = 0, r = userName.length - 1; r < pass1.length; l++, r++) {
			var flag = true;

			for (let i = l; i <= r; i++) {
				if (userName[i - l] != pass1[i]) {
					flag = false;
					break;
				}
			}

			if (flag) {
				alert("Your password can’t be too similar to your other personal information.");
				return false;
			}
		}

		//  checking email
		let email = document.getElementById("id_email").value;
		response = JSON.parse(ajaxRequest("/accounts/checkEmail/", {
			"email": email,
		}));


		if (response["cnt"] > 0) {
			alert("same email already exists");
			return false;
		}

		return true;
	}

	function changeType(icon, container) {
		if (container.type == "password") {
			icon.className = "fa fa-eye-slash text-primary";
			container.type = "text";
		} else {
			icon.className = "fa fa-eye text-primary";
			container.type = "password";
		}
	}

	function ajaxRequest(_url, _data) {
		const token = '{{csrf_token}}';

		return request = $.ajax({
			headers: {
				"X-CSRFToken": token
			},
			url: _url,
			type: "post",
			data: _data,
			async: false,
		}).responseText;
	}
</script>

{%endblock%}

templates/accounts/otpConfirm.html
{% extends 'accounts/basic.html' %}
{% load static %}
{% block title %}{{title}}{% endblock %}


{% block css %}{%endblock%}

{%block header%}
<header class="site-header mo-left header">
    <div class="sticky-header main-bar-wraper header-curve navbar-expand-lg">
        <div class="main-bar clearfix bg-primary">
            <div class="container clearfix">
                <!-- website logo -->
                <div class="logo-header mostion">
					<a href="/"><img src="{%static 'images/logo.png'%}" alt="" style="height: 72px; width: 72px;"></a>
                </div>

                <!-- main nav -->
                <div class="header-nav navbar-collapse collapse justify-content-end" id="navbarNavDropdown">
                    <div class="logo-header d-md-block d-lg-none">
                        <a href="/"><img src="{%static 'images/logo.png'%}" alt="" style="height: 72px; width: 72px;"></a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li> <a href="/">Home</a></li>
                        <li> <a href="/blogs">Blogs</a></li>
                        <li> <a href="/newsletters">Newsletters</a></li>
                        <li> <a href="/contest">Contests</a></li>
                        {%if user.is_authenticated%}
                        <li> <a href="/accounts/logout">Logout</a></li>
                        {%else%}
                        <li> <a href="/accounts/login">Login</a></li>
                        {%endif%}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

{%endblock%}


{% block body%}
<div class="section-full content-inner contact-page-8 bg-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-12">
                <div class="row">
                    <div class="col-lg-12 col-md-12 m-b30">
                        <div class="icon-bx-wraper expertise bx-style-1 p-a20 radius-sm">
                            <div class="icon-content">
                                <h5 class="dlab-tilte">
                                    <span class="icon-sm text-primary"><i class="ti-location-pin"></i></span>
                                    NIT, JALANDHAR
                                </h5>
                                <p>Grand Trunk Road, Barnala - Amritsar Bypass Rd, Jalandhar, Punjab 144011 / India </p>
                                <h6 class="m-b15 text-black font-weight-400"><i class="ti-alarm-clock"></i> Office Hours
                                </h6>
                                <p class="m-b0">Mon To Sun - 24 Hr</p>
                                <p>National Holidays - Closed</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-6 m-b30">
                        <div class="icon-bx-wraper expertise bx-style-1 p-a20 radius-sm">
                            <div class="icon-content">
                                <h5 class="dlab-tilte">
                                    <span class="icon-sm text-primary"><i class="ti-email"></i></span>
                                    E-mail
                                </h5>
                                <p class="m-b0">webmaster@nitj.ac.in</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-6 m-b30">
                        <div class="icon-bx-wraper expertise bx-style-1 p-a20 radius-sm">
                            <div class="icon-content">
                                <h5 class="dlab-tilte">
                                    <span class="icon-sm text-primary"><i class="ti-mobile"></i></span>
                                    Phone Numbers
                                </h5>
                                <p class="m-b0">+91-181-2690324</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-8 col-md-12 m-b30" id="form_container">
                <form class="inquiry-form wow fadeInUp" data-wow-delay="0.2s" action="/accounts/addUser/" method="POST"
                    enctype="multipart/form-data" onsubmit="return VerifyOTP();">
                    {% csrf_token %}
                    <h3 class="title-box font-weight-300 m-t0 m-b10">CONFIRM OTP <span class="bg-primary"></span></h3>
                    <p>AN OTP HAS BEEN SENT TO YOUR EMAIL - <b> {{email}}</b></p>
                    <p>It may also sent to your spam box</p>
                    <div class="row">
                        <input name="username" type="text" required class="form-control" placeholder="User Name"
                            id="id_username" value="{{username}}" style="display: none;">
                        <input name="password1" type="password" required class="form-control" placeholder="Password"
                            id="id_password1" value="{{password}}" style="display: none;">
                        <input name="password2" type="password" required class="form-control" placeholder="Password"
                            id="id_password1" value="{{password}}" style="display: none;">
                        <input name="firstName" type="text" required class="form-control" placeholder="First Name"
                            id="id_firstName" value="{{firstName}}" style="display: none;">
                        <input name="lastName" type="text" class="form-control" placeholder="Last Name" id="id_lastName"
                            value="{{lastName}}" style="display: none;">
                        <input name="email" type="email" class="form-control" required placeholder="Your Email Id"
                            id="id_email" value="{{email}}" style="display: none;">
                        <input name="phone" type="tel" class="form-control" required placeholder="Phone" id="id_phone"
                            value="{{phone}}" style="display: none;">

                        <!-- resume -->
                        <div class="col-lg-12 col-md-12">
                            <div class="form-group">
                                <div class="input-group" id="div_id_resume">
                                    <span class="input-group-addon"><i class="ti-file text-primary"></i></span>
                                    &nbsp;&nbsp;&nbsp;
                                    <input name="resume" type="file" required class="form-control"
                                        placeholder="Upload Resume" id="id_resume">
                                </div>
                            </div>
                        </div>

                        <!-- otp number -->
                        <div class="col-lg-12 col-md-12">
                            <div class="form-group">
                                <div class="input-group" id="div_id_phone">
                                    <span class="input-group-addon"><i class="ti-key text-primary"></i></span>
                                    <input name="otp" type="text" class="form-control" required placeholder="OTP"
                                        id="id_otp">
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12">
                            <button name="submit" type="submit" value="Submit" class="site-button button-md">
                                <span>Confirm OTP!</span> </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}


{% block footer%}
<!-- Footer -->
<footer class="site-footer footer-full">
	<div class="p-tb60 bg-black">
		<div class="container">
			<div class="row">
				<div class="col-md-6 text-md-left text-center footer-logo">
					<img src="{%static 'images/logo.png'%}" alt="" width="100">
					<p class="m-b0 m-t10">Copyright © 2021</p>
				</div>
				<div class="col-md-6 text-md-right text-center">
					<div class="widget-link ">
						<p>
							Developed By
							<a target="_blank" href="https://www.linkedin.com/in/prince-mishra-7379101ab/">Prince Mishra</a>, and
							<a target="_blank" href="https://www.linkedin.com/in/nishant-6013b61a3/">Nishant</a>
						</p>
						<p>
							Idea by
							<a target="_blank" href="https://www.linkedin.com/in/sourav-goyal-61b469196/">Sourav Goyal</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- Footer END -->
{%endblock%}



{% block script %}
<script>
    $('#id_resume').inputFileText({
        text: 'Select Resume'
    });

    function VerifyOTP() {
        var size = (document.getElementsByName("resume")[0].files[0].size / 1024);

        if (size > 300) {
            alert("resume size must be less than 300kb");
            return false;
        }

        var filename = document.getElementsByName("resume")[0].files[0].name;
        extension = filename.split('.').pop();

        if (extension != "pdf") {
            alert("only pdf format files are accepted");
            return false;
        }

        let OTP = `{{otp}}`
        let otp = document.getElementById("id_otp").value
        
        if (otp != OTP) {
            alert("OTP is not correct");   
            return false;
        }

        return true;
    }
</script>

{%endblock%}